export const BOOK_THUMBNAIL_UNAVAILABLE_SRC = "/cover-unavailable.png";

export const SIGNALR_MESSAGES = {
    BOOK_ADDED: "BOOK_ADDED",
    BOOK_MODIFIED: "BOOK_MODIFIED",
    BOOK_REMOVED: "BOOK_REMOVED",
};
